# Generated by Django 4.2 on 2024-04-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_name',
        ),
        migrations.AlterField(
            model_name='products',
            name='pinned_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='pinned_userid',
            field=models.TextField(default=''),
        ),
    ]
